name: Create Release Artifact

on:
  release:
    type: [published]

jobs:
  create-release-artifact:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build using Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .

      - name: run linter [flake8]
        run: flake8 .

      - name: run unit tests [pytest]
        run: pytest

      - name: create build artifact [sdist]
        run: python setup.py sdist

      - name: get release name
        id: get_release_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: limbus-${{ steps.get_release_name.outputs.VERSION }}
          path: dist/*
